[package]
name = "merging-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
merging-board-logic = { path = "../logic" }
minimax-alpha-beta = { version = "0.2.0", default-features = false }
log = "0.4.21"
